"""Namespaced SDK attribute names and OpenInference attribute key helpers.

Single source of truth: the names live in ``aiobs_contracts`` (shared with the
backend). This module re-exports them plus the OpenInference semantic-convention
constants the SDK relies on, and keeps the payload-redaction helper.
"""

from aiobs_contracts import (  # noqa: F401
    DOCUMENT_CONTENT,
    EXCEPTION_EVENT_NAME,
    EXCEPTION_MESSAGE,
    EXCEPTION_STACKTRACE,
    EXCEPTION_TYPE,
    INPUT_MIME_TYPE,
    INPUT_VALUE,
    LLM_INPUT_MESSAGES,
    LLM_INVOCATION_PARAMETERS,
    LLM_MODEL_NAME,
    LLM_OUTPUT_MESSAGES,
    LLM_PROVIDER,
    LLM_SYSTEM,
    LLM_TOKEN_COUNT_COMPLETION,
    LLM_TOKEN_COUNT_PROMPT,
    LLM_TOKEN_COUNT_TOTAL,
    MESSAGE_CONTENT,
    MESSAGE_ROLE,
    METADATA,
    OI_SPAN_KIND,
    OUTPUT_MIME_TYPE,
    OUTPUT_VALUE,
    SDK_CAPTURE_PROMPTS,
    SDK_CLIENT_ID,
    SDK_ERROR_KIND,
    SDK_ERROR_MESSAGE,
    SDK_ERROR_TYPE,
    SDK_HITL_CHECKPOINT_ID,
    SDK_HITL_INTERRUPT_PAYLOAD,
    SDK_HITL_INTERRUPTED,
    SDK_HITL_NODE,
    SDK_HITL_RESUME_VALUE,
    SDK_HITL_RESUMED,
    SDK_HITL_THREAD_ID,
    SDK_PROJECT_ID,
    SDK_RETRY_COUNT,
    SDK_RETRY_OF,
    SDK_WORKFLOW_ID,
    SDK_WORKFLOW_VERSION,
    SESSION_ID,
    TOOL_NAME,
    TOOL_PARAMETERS,
    USER_ID,
    is_payload_attribute,
)

__all__ = [
    "SDK_CLIENT_ID",
    "SDK_PROJECT_ID",
    "SDK_WORKFLOW_ID",
    "SDK_WORKFLOW_VERSION",
    "SDK_CAPTURE_PROMPTS",
    "SDK_ERROR_TYPE",
    "SDK_ERROR_MESSAGE",
    "SDK_ERROR_KIND",
    "SDK_RETRY_OF",
    "SDK_RETRY_COUNT",
    "SDK_HITL_THREAD_ID",
    "SDK_HITL_INTERRUPTED",
    "SDK_HITL_RESUMED",
    "SDK_HITL_INTERRUPT_PAYLOAD",
    "SDK_HITL_RESUME_VALUE",
    "SDK_HITL_NODE",
    "SDK_HITL_CHECKPOINT_ID",
    "OI_SPAN_KIND",
    "SESSION_ID",
    "USER_ID",
    "METADATA",
    "INPUT_VALUE",
    "INPUT_MIME_TYPE",
    "OUTPUT_VALUE",
    "OUTPUT_MIME_TYPE",
    "LLM_INPUT_MESSAGES",
    "LLM_OUTPUT_MESSAGES",
    "LLM_MODEL_NAME",
    "LLM_PROVIDER",
    "LLM_SYSTEM",
    "LLM_INVOCATION_PARAMETERS",
    "LLM_TOKEN_COUNT_PROMPT",
    "LLM_TOKEN_COUNT_COMPLETION",
    "LLM_TOKEN_COUNT_TOTAL",
    "TOOL_NAME",
    "TOOL_PARAMETERS",
    "MESSAGE_CONTENT",
    "MESSAGE_ROLE",
    "EXCEPTION_TYPE",
    "EXCEPTION_MESSAGE",
    "EXCEPTION_STACKTRACE",
    "EXCEPTION_EVENT_NAME",
    "CHAIN_KIND",
    "is_payload_attribute",
]

# Span-kind value the SDK itself creates for workflow roots and manual spans.
CHAIN_KIND = "CHAIN"

# Backward-compatible alias for the OpenInference span-kind attribute name.
OPENINFERENCE_SPAN_KIND = OI_SPAN_KIND