"""pricing history, budget periods, unpriced calls, jsonb, metric uniqueness

Revision ID: 01338c231eb6
Revises: e9380502dd94
Create Date: 2026-09-15 13:50:55.443690
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '01338c231eb6'
down_revision = 'e9380502dd94'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'budgets',
        sa.Column('period_type', sa.String(length=16), nullable=False, server_default='month'),
    )
    op.add_column('cost_records', sa.Column('unit_prices', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('ix_daily_dim'), table_name='daily_metrics')
    op.create_unique_constraint('uq_daily_dim', 'daily_metrics', ['day', 'dimension', 'dimension_key'], postgresql_nulls_not_distinct=True)
    op.add_column(
        'executions',
        sa.Column('unpriced_calls', sa.Integer(), nullable=False, server_default='0'),
    )
    op.alter_column('executions', 'metadata_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('spans', 'attributes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spans', 'attributes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('executions', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('executions', 'unpriced_calls')
    op.drop_constraint('uq_daily_dim', 'daily_metrics', type_='unique')
    op.create_index(op.f('ix_daily_dim'), 'daily_metrics', ['day', 'dimension', 'dimension_key'], unique=False)
    op.drop_column('cost_records', 'unit_prices')
    op.drop_column('budgets', 'period_type')
    # ### end Alembic commands ###