"""agent dimension per project

Revision ID: a445f80da69f
Revises: 3265037ef057
Create Date: 2026-09-15 14:39:20.466918
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'a445f80da69f'
down_revision = '3265037ef057'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Agent rows are attribution metadata (names/first-last seen), rebuilt from
    # subsequent ingest; clear them so the NOT NULL column can be added safely.
    op.execute("DELETE FROM agents")
    op.add_column('agents', sa.Column('project_id', sa.String(length=32), nullable=False))
    op.drop_index(op.f('ix_agents_name'), table_name='agents')
    op.create_index(op.f('ix_agents_name'), 'agents', ['name'], unique=False)
    op.create_index(op.f('ix_agents_project_id'), 'agents', ['project_id'], unique=False)
    op.create_unique_constraint('uq_agent_project_name', 'agents', ['project_id', 'name'])
    op.create_foreign_key(
        'fk_agents_project_id', 'agents', 'projects', ['project_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_agents_project_id', 'agents', type_='foreignkey')
    op.drop_constraint('uq_agent_project_name', 'agents', type_='unique')
    op.drop_index(op.f('ix_agents_project_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_name'), table_name='agents')
    op.create_index(op.f('ix_agents_name'), 'agents', ['name'], unique=True)
    op.drop_column('agents', 'project_id')
    # ### end Alembic commands ###