"""initial schema

Revision ID: e9380502dd94
Revises: 
Create Date: 2026-09-09 16:02:56.551136
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'e9380502dd94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_name'), 'agents', ['name'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('rule_id', sa.String(length=120), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('dimension', sa.String(length=40), nullable=False),
    sa.Column('dimension_key', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_rule_id'), 'alerts', ['rule_id'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_triggered_at'), 'alerts', ['triggered_at'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('external_key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_external_key'), 'clients', ['external_key'], unique=True)
    op.create_table('daily_metrics',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('dimension', sa.String(length=40), nullable=False),
    sa.Column('dimension_key', sa.String(length=120), nullable=True),
    sa.Column('executions', sa.Integer(), nullable=False),
    sa.Column('failed_executions', sa.Integer(), nullable=False),
    sa.Column('error_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('llm_calls', sa.Integer(), nullable=False),
    sa.Column('tool_calls', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('avg_duration_ms', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('p50_duration_ms', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('p95_duration_ms', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('p99_duration_ms', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_daily_dim', 'daily_metrics', ['day', 'dimension', 'dimension_key'], unique=False)
    op.create_index(op.f('ix_daily_metrics_day'), 'daily_metrics', ['day'], unique=False)
    op.create_index(op.f('ix_daily_metrics_dimension'), 'daily_metrics', ['dimension'], unique=False)
    op.create_table('pricing',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=160), nullable=False),
    sa.Column('model_match', sa.String(length=16), nullable=False),
    sa.Column('input_price_per_1m', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('output_price_per_1m', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('cache_read_price_per_1m', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('cache_write_price_per_1m', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('reasoning_price_per_1m', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_model'), 'pricing', ['model'], unique=False)
    op.create_index(op.f('ix_pricing_provider'), 'pricing', ['provider'], unique=False)
    op.create_index('ix_pricing_provider_model', 'pricing', ['provider', 'model'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('team_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('api_key_hash', sa.String(length=128), nullable=True),
    sa.Column('api_key_label', sa.String(length=120), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_project_id'), 'projects', ['project_id'], unique=True)
    op.create_index(op.f('ix_projects_team_id'), 'projects', ['team_id'], unique=False)
    op.create_table('budgets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=True),
    sa.Column('client_id', sa.String(length=32), nullable=True),
    sa.Column('workflow_name', sa.String(length=160), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('period', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budgets_client_id'), 'budgets', ['client_id'], unique=False)
    op.create_index(op.f('ix_budgets_period'), 'budgets', ['period'], unique=False)
    op.create_index(op.f('ix_budgets_project_id'), 'budgets', ['project_id'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('version', sa.String(length=80), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_project_id'), 'workflows', ['project_id'], unique=False)
    op.create_table('executions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('trace_id', sa.String(length=32), nullable=False),
    sa.Column('workflow_id', sa.String(length=120), nullable=True),
    sa.Column('session_id', sa.String(length=120), nullable=True),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('client_id', sa.String(length=32), nullable=True),
    sa.Column('workflow_name', sa.String(length=160), nullable=True),
    sa.Column('workflow_ref', sa.String(length=32), nullable=True),
    sa.Column('workflow_version', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('root_error_kind', sa.String(length=40), nullable=True),
    sa.Column('root_error_message', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('llm_calls', sa.Integer(), nullable=False),
    sa.Column('tool_calls', sa.Integer(), nullable=False),
    sa.Column('retrieval_calls', sa.Integer(), nullable=False),
    sa.Column('agent_calls', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workflow_ref'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executions_client_id'), 'executions', ['client_id'], unique=False)
    op.create_index(op.f('ix_executions_project_id'), 'executions', ['project_id'], unique=False)
    op.create_index(op.f('ix_executions_started_at'), 'executions', ['started_at'], unique=False)
    op.create_index(op.f('ix_executions_status'), 'executions', ['status'], unique=False)
    op.create_index(op.f('ix_executions_trace_id'), 'executions', ['trace_id'], unique=True)
    op.create_table('cost_records',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('execution_id', sa.String(length=32), nullable=False),
    sa.Column('span_id', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=160), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('price_version', sa.String(length=32), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_records_execution_id'), 'cost_records', ['execution_id'], unique=False)
    op.create_index(op.f('ix_cost_records_span_id'), 'cost_records', ['span_id'], unique=False)
    op.create_table('spans',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('execution_id', sa.String(length=32), nullable=False),
    sa.Column('trace_id', sa.String(length=32), nullable=False),
    sa.Column('span_id', sa.String(length=16), nullable=False),
    sa.Column('parent_id', sa.String(length=16), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_type', sa.String(length=200), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_kind', sa.String(length=40), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('llm_model', sa.String(length=120), nullable=True),
    sa.Column('llm_provider', sa.String(length=80), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=160), nullable=True),
    sa.Column('retrieval_doc_count', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spans_execution_id'), 'spans', ['execution_id'], unique=False)
    op.create_index(op.f('ix_spans_kind'), 'spans', ['kind'], unique=False)
    op.create_index(op.f('ix_spans_parent_id'), 'spans', ['parent_id'], unique=False)
    op.create_index(op.f('ix_spans_span_id'), 'spans', ['span_id'], unique=False)
    op.create_index(op.f('ix_spans_trace_id'), 'spans', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spans_trace_id'), table_name='spans')
    op.drop_index(op.f('ix_spans_span_id'), table_name='spans')
    op.drop_index(op.f('ix_spans_parent_id'), table_name='spans')
    op.drop_index(op.f('ix_spans_kind'), table_name='spans')
    op.drop_index(op.f('ix_spans_execution_id'), table_name='spans')
    op.drop_table('spans')
    op.drop_index(op.f('ix_cost_records_span_id'), table_name='cost_records')
    op.drop_index(op.f('ix_cost_records_execution_id'), table_name='cost_records')
    op.drop_table('cost_records')
    op.drop_index(op.f('ix_executions_trace_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_status'), table_name='executions')
    op.drop_index(op.f('ix_executions_started_at'), table_name='executions')
    op.drop_index(op.f('ix_executions_project_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_client_id'), table_name='executions')
    op.drop_table('executions')
    op.drop_index(op.f('ix_workflows_project_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_budgets_project_id'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_period'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_client_id'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_projects_team_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('teams')
    op.drop_index('ix_pricing_provider_model', table_name='pricing')
    op.drop_index(op.f('ix_pricing_provider'), table_name='pricing')
    op.drop_index(op.f('ix_pricing_model'), table_name='pricing')
    op.drop_table('pricing')
    op.drop_index(op.f('ix_daily_metrics_dimension'), table_name='daily_metrics')
    op.drop_index(op.f('ix_daily_metrics_day'), table_name='daily_metrics')
    op.drop_index('ix_daily_dim', table_name='daily_metrics')
    op.drop_table('daily_metrics')
    op.drop_index(op.f('ix_clients_external_key'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_alerts_triggered_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_rule_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_agents_name'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###